name: AGCore
version: 2.0
main: Core.Main
description: AGCore

commands:
    agtest:
        description: Is AGCore active?
    servers:
        description: Opens server list menu
    check:
        description:  Checks players personal Stats.
    setspawn:
        description: Sets the players current location to the Config
    spawn:
        description: Teleports the player to the set location    
