name: AGCore
version: 5.0.2
main: Core.Core
description: AGCore

commands:
    servers:
        description: Opens server list menu
        permission: core.servers
    setspawn:
        description: Sets the players current location to the Config
        permission: core.setspawn
    spawn:
        description: Teleports the player to the set location    
        permission: core.spawn
    lp:
        description: Usage >> /lp <enable/disable>
        permission: core.launchpads.use
    core:
        description: Usage >> /core info
        permission: core.use