name: AGCore
version: 1.1.5
main: Core.$1Listener
description: AGCore

commands:
    agtest:
        description: Is AGCore active?
    servers:
        description: Opens server list menu
    agcore:
        description: ...
    check:
        description:  Checks players personal Stats.    
