name: AGCore
version: 4.4.2
main: Core.Main
description: AGCore

commands:
    servers:
        description: Opens server list menu
    check:
        description:  Checks players personal Stats.
    setspawn:
        description: Sets the players current location to the Config
    spawn:
        description: Teleports the player to the set location    
    lp:
        description: Usage >> /lp <enable/disable>
    core:
        description: Usage >> /core info
