name: AGCore
version: 1.6.2
main: Core.Main
description: AGCore

commands:
    agtest:
        description: Is AGCore active?
    servers:
        description: Opens server list menu
    agcore:
        description: ...
    check:
        description:  Checks players personal Stats.    
